name: Budipest
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^0.1.2
  flutter_svg: any
  font_awesome_flutter: 8.4.0

  firebase_core: ^0.4.0
  firebase_analytics: any
  cloud_firestore: ^0.12.5
  geoflutterfire: 2.0.3+5
  fluster: 1.1.2

  google_maps_flutter: ^0.5.12
  location: 1.4.1

  provider: any
  get_it: any
  url_launcher: any

  shared_preferences: any
  sliding_up_panel: ^0.3.6
  uuid: 2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/

    # Marker icons - light
    - assets/icons/pin/l_gas_station_unknown.svg
    - assets/icons/pin/l_gas_station_closed.svg
    - assets/icons/pin/l_gas_station_open.svg
    - assets/icons/pin/l_general_unknown.svg
    - assets/icons/pin/l_general_closed.svg
    - assets/icons/pin/l_general_open.svg
    - assets/icons/pin/l_portable_unknown.svg
    - assets/icons/pin/l_portable_closed.svg
    - assets/icons/pin/l_portable_open.svg
    - assets/icons/pin/l_restaurant_unknown.svg
    - assets/icons/pin/l_restaurant_closed.svg
    - assets/icons/pin/l_restaurant_open.svg
    - assets/icons/pin/l_shop_unknown.svg
    - assets/icons/pin/l_shop_closed.svg
    - assets/icons/pin/l_shop_open.svg
    - assets/icons/pin/l_gas_station_unknown.svg

    # Marker icons - dark
    - assets/icons/pin/d_gas_station_closed.svg
    - assets/icons/pin/d_gas_station_open.svg
    - assets/icons/pin/d_general_unknown.svg
    - assets/icons/pin/d_general_closed.svg
    - assets/icons/pin/d_general_open.svg
    - assets/icons/pin/d_portable_unknown.svg
    - assets/icons/pin/d_portable_closed.svg
    - assets/icons/pin/d_portable_open.svg
    - assets/icons/pin/d_restaurant_unknown.svg
    - assets/icons/pin/d_restaurant_closed.svg
    - assets/icons/pin/d_restaurant_open.svg
    - assets/icons/pin/d_shop_unknown.svg
    - assets/icons/pin/d_shop_closed.svg
    - assets/icons/pin/d_shop_open.svg

    # Square icons - dark
    - assets/icons/bottom/dark/cat_general.svg
    - assets/icons/bottom/dark/cat_gas_station.svg
    - assets/icons/bottom/dark/cat_restaurant.svg
    - assets/icons/bottom/dark/cat_shop.svg
    - assets/icons/bottom/dark/cat_temporary.svg
    - assets/icons/bottom/dark/tag_babyroom.svg
    - assets/icons/bottom/dark/tag_wheelchair_accessible.svg
    - assets/icons/bottom/dark/tag_key.svg

    # Square icons - light
    - assets/icons/bottom/light/cat_general.svg
    - assets/icons/bottom/light/cat_gas_station.svg
    - assets/icons/bottom/light/cat_restaurant.svg
    - assets/icons/bottom/light/cat_shop.svg
    - assets/icons/bottom/light/cat_temporary.svg
    - assets/icons/bottom/light/tag_babyroom.svg
    - assets/icons/bottom/light/tag_wheelchair_accessible.svg
    - assets/icons/bottom/light/tag_key.svg

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  fonts:
    - family: Muli
      fonts:
        - asset: fonts/Muli-Bold.ttf
          weight: 700
        - asset: fonts/Muli-Regular.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
